/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sablon;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        jPanel1.setBackground(new java.awt.Color(0, 0, 204, 50));
        jPanel2.setBackground(new java.awt.Color(0, 0, 204, 50));
        load_table_pesanan();
        jTabbedPane1.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        warnaTxt = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JTextField();
        telpTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sizeTxt = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JComboBox<>();
        jumlahTxt = new javax.swing.JSpinner();
        hargaTxt = new javax.swing.JSpinner();
        kainTxt = new javax.swing.JComboBox<>();
        sablonTxt = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();
        searchBox = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 120, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Double klik data yang akan diedit, atau klik tab form untuk menambah data.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(830, 525));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE PEMESANAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HARGA (Rp)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 47, -1, -1));

        kodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(kodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 51, 211, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA PEMESAN ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMER HP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JENIS KAIN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("WARNA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JENIS SABLON");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("JUMLAH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        warnaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaTxtActionPerformed(evt);
            }
        });
        jPanel1.add(warnaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 276, 211, -1));

        alamatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTxtActionPerformed(evt);
            }
        });
        jPanel1.add(alamatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 145, 211, -1));

        telpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpTxtActionPerformed(evt);
            }
        });
        jPanel1.add(telpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 110, 211, -1));

        namaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTxtActionPerformed(evt);
            }
        });
        jPanel1.add(namaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 86, 211, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Tambah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 109, 109, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIZE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, -1, -1));

        sizeTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "XXL", "XXXL" }));
        jPanel1.add(sizeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 395, 211, 28));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("JENIS KELAMIN");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 441, -1, -1));

        genderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 441, 211, 28));
        jPanel1.add(jumlahTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 364, 211, -1));
        jPanel1.add(hargaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 51, 164, -1));

        kainTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton combats 30s", "Cotton combats 24s" }));
        kainTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kainTxtActionPerformed(evt);
            }
        });
        jPanel1.add(kainTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 223, 211, 28));

        sablonTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PVC", "Flock/beludru", "Glow in the dark", "PU", "Metallic", "Reflective" }));
        jPanel1.add(sablonTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 314, 211, 28));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Ubah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 151, 109, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 193, 109, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Bersihkan");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 235, -1, -1));

        jTabbedPane1.addTab("FORM", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_BARANG", "NAMA_BARANG", "HARGA", "STOK"
            }
        ));
        tblPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesanan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 1015, 592));
        jPanel2.add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 320, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("CARI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 12, -1, -1));

        jTabbedPane1.addTab("TABEL", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\1-7-1024x683.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Pemesanan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int b = JOptionPane.showConfirmDialog(this, "Anda yakin untuk LOGOUT ?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            this.dispose();
            new login().setVisible(true);
        } else if (b == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void load_table_pesanan() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Nama pemesan");
        model.addColumn("Telp");
        model.addColumn("Alamat");
        model.addColumn("Jenis kain");
        model.addColumn("Warna");
        model.addColumn("Jenis sablon");
        model.addColumn("Jumlah");
        model.addColumn("Size");
        model.addColumn("Jenis kelamin");
        model.addColumn("Harga");
        //menampilkan data database kedalam tabel
        try {
            String sql;
            if (!"".equals(searchBox.getText())) {
                sql = "select * from pemesanan where id_pesanan like '%" + searchBox.getText() + "%'"
                        + "or nama_pemesan like '%" + searchBox.getText() + "%' "
                        + "or no_hp like '%" + searchBox.getText() + "%' "
                        + "or alamat like '%" + searchBox.getText() + "%' "
                        + "or jenis_kain like '%" + searchBox.getText() + "%' "
                        + "or warna like '%" + searchBox.getText() + "%' "
                        + "or jenis_sablon like '%" + searchBox.getText() + "%' "
                        + "or jumlah like '%" + searchBox.getText() + "%' "
                        + "or size like '%" + searchBox.getText() + "%' "
                        + "or jenis_kelamin like '%" + searchBox.getText() + "%' "
                        + "or harga like '%" + searchBox.getText() + "%'";
            } else {
                sql = "select * from pemesanan";
            }
            java.sql.Connection conn = (Connection) Koneksi.bukaKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                    res.getString(9),
                    res.getString(10),
                    res.getString(11)
                });
            }
            tblPesanan.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }
    
    private void select_data(){
        int baris = tblPesanan.getSelectedRow();
        kodeTxt.setText(tblPesanan.getValueAt(baris, 0).toString());
        namaTxt.setText(tblPesanan.getValueAt(baris, 1).toString());
        telpTxt.setText(tblPesanan.getValueAt(baris, 2).toString());
        alamatTxt.setText(tblPesanan.getValueAt(baris, 3).toString());
        kainTxt.setSelectedItem(tblPesanan.getValueAt(baris, 4).toString());
        warnaTxt.setText(tblPesanan.getValueAt(baris, 5).toString());
        sablonTxt.setSelectedItem(tblPesanan.getValueAt(baris, 6).toString());
        jumlahTxt.setValue(Integer.parseInt(tblPesanan.getValueAt(baris, 7).toString()));
        sizeTxt.setSelectedItem(tblPesanan.getValueAt(baris, 8).toString());
        genderTxt.setSelectedItem(tblPesanan.getValueAt(baris, 9).toString());
        hargaTxt.setValue(Integer.parseInt(tblPesanan.getValueAt(baris, 10).toString()));
        jTabbedPane1.setSelectedIndex(0);
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String sql = "delete from pemesanan where id_pesanan = '"+kodeTxt.getText()+"'";
            Connection conn=(Connection)Koneksi.bukaKoneksi();
            PreparedStatement pst=conn.prepareStatement(sql);
            Object[] tombol = {"Hapus","Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if(yatidak == JOptionPane.NO_OPTION){
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            } else if(yatidak == JOptionPane.YES_OPTION){
                pst.execute();
                load_table_pesanan();
                EmptyForm();
                jTabbedPane1.setSelectedIndex(1);
            }
            
        } catch(HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n"+e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Connection con = Koneksi.bukaKoneksi();
            Statement st = con.createStatement();
            //tempat data ditambahkan
            String sql = "update pemesanan set"
            + " nama_pemesan = '" + namaTxt.getText() + "'"
            + ", no_hp = '" + telpTxt.getText() + "'"
            + ", alamat = '" + alamatTxt.getText() + "'"
            + ", jenis_kain = '" + kainTxt.getSelectedItem().toString() + "'"
            + ", warna = '" + warnaTxt.getText() + "'"
            + ", jenis_sablon = '" + sablonTxt.getSelectedItem().toString() + "'"
            + ", jumlah = '" + jumlahTxt.getValue().toString() + "'"
            + ", size = '" + sizeTxt.getSelectedItem().toString() + "'"
            + ", jenis_kelamin = '" + genderTxt.getSelectedItem().toString() + "'"
            + ", harga = '" + hargaTxt.getValue().toString() + "'"
            + " where id_pesanan = '" + kodeTxt.getText() + "'";

            int row = st.executeUpdate(sql);

            //pesan jika data sukses ditambahkan
            if (row == 1) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "informasi", JOptionPane.INFORMATION_MESSAGE);
                load_table_pesanan();
                jTabbedPane1.setSelectedIndex(1);
                EmptyForm();
                con.close();
            }
        } //data gagal dimasukkan pada database
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah\n" + e.getMessage(), "informasi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Tambah();
        load_table_pesanan();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTxtActionPerformed
        namaTxt.setText("");
    }//GEN-LAST:event_namaTxtActionPerformed

    private void telpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpTxtActionPerformed
        telpTxt.setText("");
    }//GEN-LAST:event_telpTxtActionPerformed

    private void alamatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTxtActionPerformed
        alamatTxt.setText("");
    }//GEN-LAST:event_alamatTxtActionPerformed

    private void warnaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnaTxtActionPerformed
        warnaTxt.setText("");
    }//GEN-LAST:event_warnaTxtActionPerformed

    private void kodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeTxtActionPerformed
        kodeTxt.setText("");
    }//GEN-LAST:event_kodeTxtActionPerformed

    private void tblPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesananMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()){
            evt.consume();
            select_data();
        }
    }//GEN-LAST:event_tblPesananMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        load_table_pesanan();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void kainTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kainTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kainTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Karyawan().setVisible(true);
        });
    }

    private void EmptyForm() {
        kodeTxt.setText("");
        namaTxt.setText("");
        telpTxt.setText("");
        alamatTxt.setText("");
        warnaTxt.setText("");
        jumlahTxt.setValue(0);
        hargaTxt.setValue(0);
//        for (Component c : jPanel1.getComponents()) {
//            for (Component sc : ((JPanel) c).getComponents()) {
//                if (sc instanceof JComboBox) {
//                    ((JComboBox) sc).setSelectedIndex(0);
//                }
//            }
//        }
    }

    void Tambah() {
        try {
            Connection con = Koneksi.bukaKoneksi();
            Statement st = con.createStatement();
            //tempat data ditambahkan
            String sql = "insert into pemesanan values('" + kodeTxt.getText() + "'"
                    + ",'" + namaTxt.getText() + "'"
                    + ",'" + telpTxt.getText() + "'"
                    + ",'" + alamatTxt.getText() + "'"
                    + ",'" + kainTxt.getSelectedItem().toString() + "'"
                    + ",'" + warnaTxt.getText() + "'"
                    + ",'" + sablonTxt.getSelectedItem().toString() + "'"
                    + ",'" + jumlahTxt.getValue().toString() + "'"
                    + ",'" + sizeTxt.getSelectedItem().toString() + "'"
                    + ",'" + genderTxt.getSelectedItem().toString() + "'"
                    + ",'" + hargaTxt.getValue().toString() + "')";

            int row = st.executeUpdate(sql);

            //pesan jika data sukses ditambahkan
            if (row == 1) {
                JOptionPane.showMessageDialog(null, "Data sudah ditambahkan ke" + "database", "informasi", JOptionPane.INFORMATION_MESSAGE);
                EmptyForm();
                con.close();
            }
        } //data gagal dimasukkan pada database
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan ke" + "database\n" + e.getMessage(), "informasi", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTxt;
    private javax.swing.JComboBox<String> genderTxt;
    private javax.swing.JSpinner hargaTxt;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jumlahTxt;
    private javax.swing.JComboBox<String> kainTxt;
    private javax.swing.JTextField kodeTxt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JComboBox<String> sablonTxt;
    private javax.swing.JTextField searchBox;
    private javax.swing.JComboBox<String> sizeTxt;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JTextField telpTxt;
    private javax.swing.JTextField warnaTxt;
    // End of variables declaration//GEN-END:variables
}
