/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sablon;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        jPanel1.setBackground(new java.awt.Color(0,0,204,50));
        
    }
    
    private void goToPage(String page) {
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), page);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userPemilik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLoginPemilik = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        passPemilik = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userKaryawan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLoginKaryawan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        passKaryawan = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN Sebagai Pemilik");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 133, -1));
        jPanel1.add(userPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 260, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        btnLoginPemilik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLoginPemilik.setText("LOGIN");
        btnLoginPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPemilikActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 109, 33));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Login sebagai karyawan");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 228, 33));
        jPanel1.add(passPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 258, 31));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\1-7-1024x683.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, "pemilik");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN Sebagai Karyawan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USERNAME");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 133, -1));
        jPanel2.add(userKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 260, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PASSWORD");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        btnLoginKaryawan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLoginKaryawan.setText("LOGIN");
        btnLoginKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginKaryawanActionPerformed(evt);
            }
        });
        jPanel2.add(btnLoginKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 109, 33));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Login sebagai pemilik");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 222, 33));
        jPanel2.add(passKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 256, 32));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\1-7-1024x683.jpg")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, "karyawan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        goToPage("pemilik");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        goToPage("karyawan");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLoginKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginKaryawanActionPerformed
        try {
            String passValue = String.valueOf(passKaryawan.getPassword());
            String sql = "select * from karyawan where Nama = ? and Password = ?";
            Connection conn = (Connection)Koneksi.bukaKoneksi();
            
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setString(1, userKaryawan.getText());
            stm.setString(2, passValue);
            ResultSet res = stm.executeQuery();
            boolean masuk = false;
            masuk = res.next();
            if (masuk){
                this.dispose();
                new Karyawan().setVisible(true);
            } else{
                JOptionPane.showMessageDialog(this, "Username/password salah", "Error",0);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",0);
        }
    }//GEN-LAST:event_btnLoginKaryawanActionPerformed

    private void btnLoginPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPemilikActionPerformed
        try {
            String passValue = String.valueOf(passPemilik.getPassword());
            String sql = "select * from pemilik where Nama = ? and Password = ?";
            Connection conn = (Connection)Koneksi.bukaKoneksi();
            
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setString(1, userPemilik.getText());
            stm.setString(2, passValue);
            ResultSet res = stm.executeQuery();
            boolean masuk = false;
            masuk = res.next();
            if (masuk){
                this.dispose();
                new Pemilik().setVisible(true);
            } else{
                JOptionPane.showMessageDialog(this, "Username/password salah", "Error",0);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",0);
        }
    }//GEN-LAST:event_btnLoginPemilikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginKaryawan;
    private javax.swing.JButton btnLoginPemilik;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passKaryawan;
    private javax.swing.JPasswordField passPemilik;
    private javax.swing.JTextField userKaryawan;
    private javax.swing.JTextField userPemilik;
    // End of variables declaration//GEN-END:variables
}
